In [1]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

Series is one of the important data structure in Pandas.
It is essentily a <b>1-dimensinal labeled array</b> --capable of holding anay data type (integers,strings,floats etc)

Think of it like a single column of a table with labels (index)

--Each value in series is associated with a index.

--Easy for retrieval and manipulations .


What is a Pandas Series?

A Series constists of 2 main parts.

1.Data   -- values
2.Index  -- labels

Ex:
Index       Value
0           10
1           20
2           30

Import pandas as pd

In [ ]:
#Empty series 
import pandas as pd
ser=pd.Series()
print(ser)

Series([], dtype: object)

In [3]:
#Creating series from list.
data = [10,20,30,40]
s=pd.Series(data)
print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [ ]:
#Custom index in pandas series
s = pd.Series([10,20,30],index=['a','b','c'])
print(s)

a    10
b    20
c    30
dtype: int64

In [6]:
#Create a series from dictionary
data ={'z':10,'y':20,'x':30}

s=pd.Series(data)
print(s)

z    10
y    20
x    30
dtype: int64

In [ ]:
#creting series using range fun()
ser=pd.Series(range(4,10))
print(ser)

0    4
1    5
2    6
3    7
4    8
5    9
dtype: int64

In [ ]:
# Create a Series using List Comprehension
ser=pd.Series(range(1,20,3),index=[x for x in 'zxyabce'])
print(ser)

z     1
x     4
y     7
a    10
b    13
c    16
e    19
dtype: int64

In [9]:
# Create a series using Numpy Array.
import numpy as np
data=np.array(['v','r','j','a'])
ser=pd.Series(data)
print(ser)

0    v
1    r
2    j
3    a
dtype: object

Accessing elements of pandas Series.

---One dim labeled array   --- index ,custom index .

--Labels need to be unique but must be a hashable type.

--Like as ndarray similary we can access elements.

2 ways to access elements in series

1.Acccessing Element from Series with Position
2.Accessing Elemnts Using Label (index)

In [ ]:
import pandas as pd

s=pd.Series([10,20,30,40],index=['a','b','c','d'])
print(s)

#Index -->a,b,c,d
#Values -->10,20,30,40

a    10
b    20
c    30
d    40
dtype: int64

In [ ]:
#Access A Single label  ---> Label based indexing
print(s['a']," ",s['d'])

10   40

In [ ]:
# Accessing Multiple Elements.  -->pass list of labels -->access Multiple Elements.

print(s[['a','b','c']])

a    10
b    20
c    30
dtype: int64

In [ ]:
#Accessing Using Position  --(Integer Index)  -- iloc()   --elements based on position.
# Try to access labeled based Name Error.Out of Index --Index out of exception#
#print(s.iloc[5])
print(s.iloc[1])

#Postion starts from 0 

#Mutiple positions using iloc()
print(s.iloc[[0,2]])

#Accessing as A Range (Slicing)
print(s.iloc[1:3])

#Start index is included here and End index is excluded.

20
a    10
c    30
dtype: int64
b    20
c    30
dtype: int64

In [29]:
# Using Labels   -- loc()
# Index which is not there or use integer based --Key error#

print(s.loc['b'])
print(s.loc[['b','a']])
print(s.loc['b':'d'])

#print(s.loc['e'])

20
b    20
a    10
dtype: int64
b    20
c    30
d    40
dtype: int64

Impotant aspect :

Method              End Included
iloc                No
loc                 Yes.

Boolean Indexing (Conditional absed Access)

Filter elemnts using condition (Relation operators)

Accessing them using at .

at is used for fast access of a single value ---using label

iat is used for fast access using position

In [31]:
print(s[s <= 20])

a    10
b    20
dtype: int64

In [32]:
print(s.at['d'])

40

In [33]:
print(s.iat[1])

20

In [36]:
# Accessing First and Last ELements.
print(s.iloc[0])
print(s.iloc[-1])

10
40

In [37]:
# Accessing Elemnts using custom conditions

s=pd.Series([5,10,15,20,25,30,35])

print(s[s % 2 == 0])

1    10
3    20
5    30
dtype: int64

In [38]:
# Check if Index Exists.
print('a' in s)

False

loc -->labels
iloc-->integer positions.

In [41]:
# Check the data types of A series

print(s.dtype)

#Get index of a series
print(s.index)

#Filter values in a series

print(s[s > 20])

int64
RangeIndex(start=0, stop=7, step=1)
4    25
5    30
6    35
dtype: int64

In [42]:
# Perform arthimatic operations on series
s=pd.Series([1,2,3,4])
print( s* 2)

0    2
1    4
2    6
3    8
dtype: int64

Binary opeations on Series.

---Arthimatic operations : Addition,sub.mul,div etc.
---Compaision Operations: +,!=,>,<,=>,<=
---Logical operators :ANd or etc.

In [ ]:
# Adding 2 Series.---Both series have same indexes ---Erro but you see conrtesion data.
s1=pd.Series([10,20,30],index=['a','b','c'])
s2=pd.Series([1,2,3],index=['a','b','c'])
#s2=pd.Series([1,2,3],index=['z','y','x'])

result =s1+s2
print(result)

a   NaN
b   NaN
c   NaN
x   NaN
y   NaN
z   NaN
dtype: float64

In [54]:
#Comparision Operations.
s1=pd.Series([10,20,30])
s2=pd.Series([10,25,30])


#result = s1 == s2
result = s1  >= s2

print(result)

0     True
1    False
2     True
dtype: bool

In [55]:
# Logical operators:
s1=pd.Series([True,False,True])
s2=pd.Series([False,False,True])

result=s1 & s2
print(result)

0    False
1    False
2     True
dtype: bool

Series Index Attibute:
---One dimenninal array capable of holding any data type (integers,strings,floats etc)
--If each element having an assiciated label known as Index.
--We can set Index and Get Index.

In [60]:
data = pd.Series([10,20,30,40],index=['a','b','c','d'])

# Accesing the index
print("Original Index",data.index)


#Modify the index.
data.index=['w','x','y','z']
print("modified series\n",data)

Original Index Index(['a', 'b', 'c', 'd'], dtype='object')
modified series
 w    10
x    20
y    30
z    40
dtype: int64

Syntax:
Series.index  ---Access index labels.
Series.index=new_index # Modify index labels


It will not take anay params.
It return labels of series.

---Retrieve the current index lable of series.
---Can be used to set new index.
---Support both unique and duplicate index labels.
---Usefull for locate elements efficiently.

In [65]:
# Assigning Duplicate Index for pandas Series.
series=pd.Series(['Bangaore','Hyd','Delhi','Mysure'])

print(series)
#Creating the row axis labels.
series.index=['city1','city1','city2','city2']
print(series)

print(series.index)

# Resetting Index to defualt.

series.reset_index(drop=True,inplace=True)
print(series)

0    Bangaore
1         Hyd
2       Delhi
3      Mysure
dtype: object
city1    Bangaore
city1         Hyd
city2       Delhi
city2      Mysure
dtype: object
Index(['city1', 'city1', 'city2', 'city2'], dtype='object')
0    Bangaore
1         Hyd
2       Delhi
3      Mysure
dtype: object

In [72]:
s1=pd.Series([10,20,30],index=["A","B","C"])
s2=pd.Series([1,2,3],index=["B","C","D"])

print(s1+s2)

# Length of index.
print(len(s1.index))

# Coverting index to list
list(s1.index)

# Index is immutable

#s.index[0]="A"

#But we can eplace the whole index.
s1.index=["x","y","z"]
print(s1.index)

A     NaN
B    21.0
C    32.0
D     NaN
dtype: float64
3
Index(['x', 'y', 'z'], dtype='object')

In [80]:
import pandas as pd
import numpy as np
data=np.array(['a','b','c','d'])
#s=pd.Series(data)
s=pd.Series(data,index=[1000,1001,1002,1003])
print(s)

print(s.values)
print(s.dtype)
print(s.name)
print(s.shape)
print(s.size)
print(s.ndim)

1000    a
1001    b
1002    c
1003    d
dtype: object
['a' 'b' 'c' 'd']
object
None
(4,)
4
1

In [85]:
s=pd.Series([10,20,30,40,50,60])

s1=pd.Series([10,20,30],index=["A","B","c"])

print(s1.index)

print(s.index)

Index(['A', 'B', 'c'], dtype='object')
RangeIndex(start=0, stop=6, step=1)

In [ ]:
# Usefull operations.
s=pd.Series([1,2,3,1,1,2,3,4,2,1,3,4,5,6,5])

s.unique()  # Unique value sin array format.
s.nunique() # Count of unique values.
s.value_counts() # Frequency count
s.nlargest(3)  # top 3
s.nsmallest(3)  # bottom 3
s.clip(lower=2,upper=5)  # Clip outliers

#s.map({1:'one',2:'two'})   # Map vlaues

0     one
1     two
2     NaN
3     one
4     one
5     two
6     NaN
7     NaN
8     two
9     one
10    NaN
11    NaN
12    NaN
13    NaN
14    NaN
dtype: object

Main Data Structures in pandas are
1.Series (1 Dimensional array ) ---repesents columns of table
2.DataFrame (2 Dimensional array)

What is DataFrame ?

A DataFrame is 2  dimensional labeled data structure simalr to table in a DB or spreadsheet.

It reresnts table.

Rows --Index
Columns 
Values

Example:
ID   Name   Age
1    Alice   22
2    Bob     25
3    Charlie 30

In [99]:
import pandas as pd
import numpy as np
data = {
    "Name":["Alice","Bob","Charlie"],
    "Age":[22,25,30],
    "City":["Newyork","Bangalore","Hyd"]
}
#Creating Data from list
data1=[
    ["Alice",22],
    ["Bob",25],
    ["Charlie",30]
]
#Creating data from List of Dictionaries
data2=[
    {"Name":"Alice","Age":22},
    {"Name":"Bob","Age":25}
]
df=pd.DataFrame(data2)
print(df)

# Empty DF.

df=pd.DataFrame()
print(df)

# create df from np arrays.
data=np.array([[1,2,3],[4,5,6],[7,8,9]])
df=pd.DataFrame(data,columns=['X','Y','Z'])
print(df)

    Name  Age
0  Alice   22
1    Bob   25
Empty DataFrame
Columns: []
Index: []
   X  Y  Z
0  1  2  3
1  4  5  6
2  7  8  9

In [105]:
import pandas as pd
import numpy as np

# From a dictionary
data = {
    'Name'  : ['Alice', 'Bob', 'Carol'],
    'Age'   : [28, 34, 25],
    'Score' : [85.5, 92.0, 78.3]
}
df = pd.DataFrame(data)
print(df)

print(df.index)

# Setting a custom Index.
df_with_index=df.set_index('Name')
print(df_with_index)

# Resetting index.
df_reset=df.reset_index()
print(df_reset)

    Name  Age  Score
0  Alice   28   85.5
1    Bob   34   92.0
2  Carol   25   78.3
RangeIndex(start=0, stop=3, step=1)
       Age  Score
Name
Alice   28   85.5
Bob     34   92.0
Carol   25   78.3
   index   Name  Age  Score
0      0  Alice   28   85.5
1      1    Bob   34   92.0
2      2  Carol   25   78.3

In [ ]:
# Accesing my DF.
df['Age']  # Single coumn --Series

df[['Name','Age']]  # Multipile column --DataFrame

df.loc[0] # Row by label
df.iloc[0] # row by integer position

df.at[0,'Age'] # Fast label scalar

df.iat[1,1]  # Fast integer scalar

np.int64(34)

In [8]:
import pandas as pd

df=pd.DataFrame({
    'Name':['Alice','Bob','Charlie','Justin'],
    'Age':[22,25,30,55],
    'City':['Newyork','Bangalore','Hyd','London'],
})
print(df)

print(df.index)

      Name  Age       City
0    Alice   22    Newyork
1      Bob   25  Bangalore
2  Charlie   30        Hyd
3   Justin   55     London
RangeIndex(start=0, stop=4, step=1)

Types of index in pandas:

1.Range index (default index from pandas :DF)

Automatically assigned (0,1,2,3....)

df.index  -->RangeIndex(start=0,stop=2,step=1)

2.Int64Index
Integer labels but those labels need to be continuous labels.
df.index=[10,20,30]

3.Index(Object Index)
String or mixed-type labels.

df.index=["a","b","c"]

4.MultiIndex (Hierchical Index)

arrays=[["A","b","C"],[1,2,3]]
index=pd.MultiIndex.form_arrays(arrays)
df=pd.DataFrame({"val":[10,20,30]},index=index)


5.DatatimeIndex.
Used for time series data.
df.index=pd.date_range("2026-01-01",periods=3)

6.CategoricalIndex 
Based on categorical data.
df.index=pd.CategoricalIndex(["A","B","C])

df.index.vlaues -- Print arrays.
df.index.name -- name of index.
df.index.shape --shape
df.index.dtype --datatype
df.index.is_unique --unique checks
df.index.has_duplicates  ---duplicates.

In [16]:
import pandas as pd

df=pd.DataFrame({
    'Name':['Alice','Bob','Charlie','Justin'],
    'Age':[22,25,30,55],
    'City':['Newyork','Bangalore','Hyd','London'],
})

#Setting a Name as index.
df.set_index('Name', inplace=True)
print(df)

print(df.index)

# Resetting index to default
df.reset_index(inplace=True)
print(df)
print(df.index)

         Age       City
Name
Alice     22    Newyork
Bob       25  Bangalore
Charlie   30        Hyd
Justin    55     London
Index(['Alice', 'Bob', 'Charlie', 'Justin'], dtype='object', name='Name')
      Name  Age       City
0    Alice   22    Newyork
1      Bob   25  Bangalore
2  Charlie   30        Hyd
3   Justin   55     London
RangeIndex(start=0, stop=4, step=1)

In [20]:
# Rename Index
df.index.name='RowID'
df.rename(index={0:'row1',1:'row2',2:'row3',3:'row4'}, inplace=True)
print(df)

# Soting index.
df.sort_index(inplace=True)

# Droping index.
df.drop(index='row2', inplace=True)
print(df)

          Name  Age       City
RowID
row1     Alice   22    Newyork
row2       Bob   25  Bangalore
row3   Charlie   30        Hyd
row4    Justin   55     London
          Name  Age     City
RowID
row1     Alice   22  Newyork
row3   Charlie   30      Hyd
row4    Justin   55   London

In [26]:
#Index Alignment   ---Pandas automatically aligns data based on the index labels when performing operations between Series or DataFrames. This means that when you add two Series together, pandas will match the index labels and perform the operation only on those labels that are present in both Series. If an index label is missing in one of the Series, the result for that label will be NaN (Not a Number). This feature allows for flexible data manipulation and ensures that operations are performed correctly even when the data is not perfectly aligned.
df1=pd.DataFrame({
    'A':[1,2,3]},index=[0,1,2])

df2=pd.DataFrame({
    'A':[4,5,6]},index=[1,2,3])

print(df1)
print(df2)
print(df1+df2)

#Indexes are immutable in pandas, which means you cannot change the index labels directly. However, you can create a new index or modify the existing one by using methods like set_index(), reset_index(), or rename(). If you try to assign a new value to an index label directly, it will raise an error. For example, if you have a DataFrame df and you try to do df.index[0] = 'new_label', it will raise a TypeError because the index is immutable. Instead, you should use df.rename() or df.set_index() to change the index labels.
#df1.index[0]=2

   A
0  1
1  2
2  3
   A
1  4
2  5
3  6
     A
0  NaN
1  6.0
2  8.0
3  NaN

In [27]:
print(df)

          Name  Age     City
RowID
row1     Alice   22  Newyork
row3   Charlie   30      Hyd
row4    Justin   55   London

In [29]:
# Single column
df['Age']

# Multiple columns
df[['Name','City']]

          Name     City
RowID
row1     Alice  Newyork
row3   Charlie      Hyd
row4    Justin   London

In [36]:
# Access row --- lable-based indexing .loc()

df.loc["row3"]

df.iloc[0]    # Position based indexing


# Using query() method to filter data based on conditions.
df.query('Age > 25')

# Using isin() method to filter data based on a list of values.
df[df['City'].isin(['Hyd','London'])]

df.Name

RowID
row1      Alice
row3    Charlie
row4     Justin
Name: Name, dtype: object

loc ---labels ---Named Index /columns --->row data
iloc ---positions --Numeric Index ---row data
at ----Label --Fast single value
iat  Position --Fast single values

In [40]:
# Fast scalar access using at and iat.
df.at['row3','Age']
df.iat[0,0]

'Alice'

---Loc with numbers is incorrect eay of doing ..
---.iloc with lables also incorrect..
---df["col"] ---column access
---loc ---labeled based access
---.iloc() -->position based access
---bolean indexing --filtering.
--- at / iat --fast scaler access.

Basic Differences:

Feature               .loc                       .iloc
Type                  Labeled-based indexing     Postion based indeing (Integer numbers)
Input                 Index/Column names         Integer position of index.
Slice                 Inclusive                  Excusive
Error                 Key Eror                   IndexEror

In [52]:
import pandas as pd
df=pd.DataFrame({
    'Name':['Alice','Bob','Charlie','Justin'],
    'Age':[22,25,30,55],
    'City':['Newyork','Bangalore','Hyd','London'],
},index=["a","b","c","d"])

#print(df)
#print(df.index)


#label-based indexing .loc()  --df.loc[row_label,column_label]
# Single row
print(df.loc["c"])
#Accessing multiple rows
print(df.loc[["a","c"]])

#Access specific value using loc
print(df.loc["c","City"])

# Access Multiple columns
print(df.loc[["a","c"],["Name","City"]])
print(df.loc[:,["Name","City"]])

# Row + column access
print(df.loc["a":"c",["Name","City"]])   # Slicing --inclusive way of slicing "a":"c"  -->c is included here. and b is taged along\
    
#Boolean filtering using loc
print(df.loc[df['Age'] > 25])    

# Conditionally select our columns
df.loc[df['Age'] > 30, ['Name','City']]

# Assign Values -- Just adding a new value to a specific cell.
df.loc["a","Age"]=20

print(df)

# Add entire row it self
df.loc["e"]=["David",40,"Chicago"]
print(df)

Name    Charlie
Age          30
City        Hyd
Name: c, dtype: object
      Name  Age     City
a    Alice   22  Newyork
c  Charlie   30      Hyd
Hyd
      Name     City
a    Alice  Newyork
c  Charlie      Hyd
      Name       City
a    Alice    Newyork
b      Bob  Bangalore
c  Charlie        Hyd
d   Justin     London
      Name       City
a    Alice    Newyork
b      Bob  Bangalore
c  Charlie        Hyd
      Name  Age    City
c  Charlie   30     Hyd
d   Justin   55  London
      Name  Age       City
a    Alice   20    Newyork
b      Bob   25  Bangalore
c  Charlie   30        Hyd
d   Justin   55     London
      Name  Age       City
a    Alice   20    Newyork
b      Bob   25  Bangalore
c  Charlie   30        Hyd
d   Justin   55     London
e    David   40    Chicago

In [64]:
# iloc -- Position based indexing  --Use integer based indexing to select data by position.(based on 0-based index)
# Basic synatx : df.iloc[row_index,column_index]
#print(df)
# Single row
print(df.iloc[0])
# Accessing multiple rows
print(df.iloc[[0,2]])

#Specific value using iloc
print(df.iloc[2,2])

# Rows + column selection
df.iloc[0:3,0:2]  # Slicing -- exclusive way of slicing 0:3 --> 3 is excluded here. and 0,1 are taged along.

#Assign values using iloc
df.iloc[0,1]=21
print(df)

Name      Alice
Age          21
City    Newyork
Name: a, dtype: object
      Name  Age     City
a    Alice   21  Newyork
c  Charlie   30      Hyd
Hyd
      Name  Age       City
a    Alice   21    Newyork
b      Bob   25  Bangalore
c  Charlie   30        Hyd
d   Justin   55     London
e    David   40    Chicago

In [ ]:
# Labels VS Postions ---loc vs iloc

#df.loc["a"]  # Label based access
df.iloc[0]   # Position based access

# Slice behaviour 
df.loc["a":"c"]  # Label based slicing --inclusive way of slicing
df.iloc[0:3]   # Position based slicing --exclusive way of slicing

# Integer Index confusions 
df1=pd.DataFrame({"A":[10,20,30]},index=[10,20,30])
df1.loc[10]  # Label based access  ---label works fine
#df1.iloc[10]  # Position based access  ---Position ---Error out of index

df1.iloc[2]

# Error 
#df1.loc[100]  # Label based access --Key error
#df1.loc["k"]

#df.iloc[10] # InterError

c:\ProgramData\anaconda3\Lib\site-packages\pandas\core\dtypes\common.py:1645: DeprecationWarning: Data type alias 'a' was deprecated in NumPy 2.0. Use the 'S' alias instead.
  npdtype = np.dtype(dtype)
c:\ProgramData\anaconda3\Lib\site-packages\pandas\core\dtypes\common.py:1645: DeprecationWarning: Data type alias 'a' was deprecated in NumPy 2.0. Use the 'S' alias instead.
  npdtype = np.dtype(dtype)

IndexError: single positional indexer is out-of-bounds

In [ ]:
# Real usage of loc and iloc
df=pd.DataFrame({
    'Name':['Alice','Bob','Charlie','Justin'],
    'Age':[22,25,30,55],
    'City':['Newyork','Bangalore','Hyd','London'],
},index=["a","b","c","d"])
print(df)
# Mixed conditions using loc
df.loc[(df['Age'] > 25) & (df['City'] == 'Hyd')]
# Select Rows using List and also slice
df.loc[["a","c"],"Name":"City"]  # Mixed selection using list and slice. Here we are selecting rows using list and columns using slice.

# Reverse
df.loc[::-1]

# Select 4 th row  df.iloc[3]  ---Select nth row df.iloc[::n-1]
df.iloc[::2]

      Name  Age       City
a    Alice   22    Newyork
b      Bob   25  Bangalore
c  Charlie   30        Hyd
d   Justin   55     London

      Name  Age     City
a    Alice   22  Newyork
c  Charlie   30      Hyd

In [84]:
# Boolean with .iloc --may not work
#df.iloc[df["Age"] > 25]   ----Not Allowed --Value Error

df.iloc[df["Age"].values > 25]   # Allowed --Works fine. It is a boolean indexing with iloc.

      Name  Age    City
c  Charlie   30     Hyd
d   Justin   55  London

When to use what time to use.

USE .loc :
We know labels.
Work with named index
Doing conditional filtering on named indexes.

Use .iloc :
When we know positions in advance
Need fast slicing
Work with pure numeric indexes.(values for conditiong)

# Coomon Mistakes.

Using .iloc with labels.
Using .loc with wrong index names
Forgetting inclusive for .loc slicing
Mixing boolean index incorrectly.

In [ ]:
data = pd.read_csv("nba.csv",index_col="Name")
data1=pd.read_excel("employee.xlsx",index_col="Name")
print("DataSet")
display(data.head(5))

# data1=pd.read_excel("employee.xlsx",index_col="Name")
# print("Excel DataSet")
# display(data1.head(5))

# first = data[["Age","College","Salary"]]
# print("\n Multiple columns from dataset\n")
# display(first.head(5))

# Single row
row = data.loc["James Young"]
print(row)

row = data.loc[["James Young","Avery Bradley"]]
print(row)

selection =data.loc[["James Young","Avery Bradley"],["Age","College","Salary"]]
print(selection)

all_rows_some_columns = data.loc[:,["Team","Position","Salary"]]
print(all_rows_some_columns)

DataSet

,Team,Number,Position,Age,Height,Weight,College,Salary
Name,,,,,,,,
Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

Team        Boston Celtics
Number                13.0
Position                SG
Age                   20.0
Height                 6-6
Weight               215.0
College           Kentucky
Salary           1749840.0
Name: James Young, dtype: object
                         Team  Number Position   Age Height  Weight   College  \
Name
James Young    Boston Celtics    13.0       SG  20.0    6-6   215.0  Kentucky
Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0     Texas

                  Salary
Name
James Young    1749840.0
Avery Bradley  7730337.0
                Age   College     Salary
Name
James Young    20.0  Kentucky  1749840.0
Avery Bradley  25.0     Texas  7730337.0
                         Team Position     Salary
Name
Avery Bradley  Boston Celtics       PG  7730337.0
Jae Crowder    Boston Celtics       SF  6796117.0
John Holland   Boston Celtics       SG        NaN
R.J. Hunter    Boston Celtics       SG  1148640.0
Jonas Jerebko  Boston Celtics       PF  5000000.0
...                       ...      ...        ...
Shelvin Mack        Utah Jazz       PG  2433333.0
Raul Neto           Utah Jazz       PG   900000.0
Tibor Pleiss        Utah Jazz        C  2900000.0
Jeff Withey         Utah Jazz        C   947276.0
NaN                       NaN      NaN        NaN

[458 rows x 3 columns]

In [100]:
row = data.iloc[3]
print(row)

row_with_multiple_columns = data.iloc[[3,5,8]]

print(row_with_multiple_columns)

specific_selection = data.iloc[[3,5,8], [0,2,4]]
print(specific_selection)

selection_full=data.iloc[:,[1,2]]
print(selection_full)

Team        Boston Celtics
Number                28.0
Position                SG
Age                   22.0
Height                 6-5
Weight               185.0
College      Georgia State
Salary           1148640.0
Name: R.J. Hunter, dtype: object
                        Team  Number Position   Age Height  Weight  \
Name
R.J. Hunter   Boston Celtics    28.0       SG  22.0    6-5   185.0
Amir Johnson  Boston Celtics    90.0       PF  29.0    6-9   240.0
Terry Rozier  Boston Celtics    12.0       PG  22.0    6-2   190.0

                    College      Salary
Name
R.J. Hunter   Georgia State   1148640.0
Amir Johnson            NaN  12000000.0
Terry Rozier     Louisville   1824360.0
                        Team Position Height
Name
R.J. Hunter   Boston Celtics       SG    6-5
Amir Johnson  Boston Celtics       PF    6-9
Terry Rozier  Boston Celtics       PG    6-2
               Number Position
Name
Avery Bradley     0.0       PG
Jae Crowder      99.0       SF
John Holland     30.0       SG
R.J. Hunter      28.0       SG
Jonas Jerebko     8.0       PF
...               ...      ...
Shelvin Mack      8.0       PG
Raul Neto        25.0       PG
Tibor Pleiss     21.0        C
Jeff Withey      24.0        C
NaN               NaN      NaN

[458 rows x 2 columns]

In [104]:
print(data.head(5))  # Display first 5 rows of the dataset.
print(data.tail(5))  # Display last 5 rows of the dataset.
value=data.at["James Young","Salary"]
print(value)

values=data.at["Avery Bradley","Age"]
print(values)

values=data.iat[0,2]
print(values)

result=data.query('Age > 30')
print(result)

                         Team  Number Position   Age Height  Weight  \
Name
Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
Jae Crowder    Boston Celtics    99.0       SF  25.0    6-6   235.0
John Holland   Boston Celtics    30.0       SG  27.0    6-5   205.0
R.J. Hunter    Boston Celtics    28.0       SG  22.0    6-5   185.0
Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0

                         College     Salary
Name
Avery Bradley              Texas  7730337.0
Jae Crowder            Marquette  6796117.0
John Holland   Boston University        NaN
R.J. Hunter        Georgia State  1148640.0
Jonas Jerebko                NaN  5000000.0
                   Team  Number Position   Age Height  Weight College  \
Name
Shelvin Mack  Utah Jazz     8.0       PG  26.0    6-3   203.0  Butler
Raul Neto     Utah Jazz    25.0       PG  24.0    6-1   179.0     NaN
Tibor Pleiss  Utah Jazz    21.0        C  26.0    7-3   256.0     NaN
Jeff Withey   Utah Jazz    24.0        C  26.0    7-0   231.0  Kansas
NaN                 NaN     NaN      NaN   NaN    NaN     NaN     NaN

                 Salary
Name
Shelvin Mack  2433333.0
Raul Neto      900000.0
Tibor Pleiss  2900000.0
Jeff Withey    947276.0
NaN                 NaN
1749840.0
25.0
PG
                                   Team  Number Position   Age Height  Weight  \
Name
Jarrett Jack              Brooklyn Nets     2.0       PG  32.0    6-3   200.0
Lou Amundson            New York Knicks    17.0       PF  33.0    6-9   220.0
Carmelo Anthony         New York Knicks     7.0       SF  32.0    6-8   240.0
Jose Calderon           New York Knicks     3.0       PG  34.0    6-3   200.0
Sasha Vujacic           New York Knicks    18.0       SG  32.0    6-7   195.0
...                                 ...     ...      ...   ...    ...     ...
Tayshaun Prince  Minnesota Timberwolves    12.0       SF  36.0    6-9   212.0
Nick Collison     Oklahoma City Thunder     4.0       PF  35.0   6-10   255.0
Randy Foye        Oklahoma City Thunder     6.0       SG  32.0    6-4   213.0
Nazr Mohammed     Oklahoma City Thunder    13.0        C  38.0   6-10   250.0
Chris Kaman      Portland Trail Blazers    35.0        C  34.0    7-0   265.0

                          College      Salary
Name
Jarrett Jack         Georgia Tech   6300000.0
Lou Amundson                 UNLV   1635476.0
Carmelo Anthony          Syracuse  22875000.0
Jose Calderon                 NaN   7402812.0
Sasha Vujacic                 NaN    947276.0
...                           ...         ...
Tayshaun Prince          Kentucky    947276.0
Nick Collison              Kansas   3750000.0
Randy Foye              Villanova   3135000.0
Nazr Mohammed            Kentucky    222888.0
Chris Kaman      Central Michigan   5016000.0

[91 rows x 8 columns]

In [105]:
import pandas as pd

player_list=[['M.S. Dhoni',39,75,'Chennai Super Kings'],
             ['Virat Kohli',34,80,'Royal Challengers Bangalore'],
                ['Rohit Sharma',33,85,'Mumbai Indians'],
                ['Suresh Raina',35,70,'Chennai Super Kings'],
                ['Jasprit Bumrah',32,80,'Mumbai Indians'],
                ['Yuvraj Singh',40,65,'Punjab Kings'],
                ['Shikhar Dhawan',36,75,'Delhi Capitals'],
                ['Ravindra Jadeja',33,75,'Chennai Super Kings'],
                ['KL Rahul',31,70,'Punjab Kings'],
                ['Hardik Pandya',32,80,'Mumbai Indians'],
                ['Rishabh Pant',25,75,'Delhi Capitals']
                    ]

df = pd.DataFrame(player_list,columns=['Player','Age','Rating','Team'])
print(df)

             Player  Age  Rating                         Team
0        M.S. Dhoni   39      75          Chennai Super Kings
1       Virat Kohli   34      80  Royal Challengers Bangalore
2      Rohit Sharma   33      85               Mumbai Indians
3      Suresh Raina   35      70          Chennai Super Kings
4    Jasprit Bumrah   32      80               Mumbai Indians
5      Yuvraj Singh   40      65                 Punjab Kings
6    Shikhar Dhawan   36      75               Delhi Capitals
7   Ravindra Jadeja   33      75          Chennai Super Kings
8          KL Rahul   31      70                 Punjab Kings
9     Hardik Pandya   32      80               Mumbai Indians
10     Rishabh Pant   25      75               Delhi Capitals

In [107]:
df1=df.iloc[0:4]
print(df1)

         Player  Age  Rating                         Team
0    M.S. Dhoni   39      75          Chennai Super Kings
1   Virat Kohli   34      80  Royal Challengers Bangalore
2  Rohit Sharma   33      85               Mumbai Indians
3  Suresh Raina   35      70          Chennai Super Kings

In [110]:
#slicing columns using iloc
df2=df.iloc[:,0:3]
print(df2)

value=df.at[0,'Player']
print(value)

             Player  Age  Rating
0        M.S. Dhoni   39      75
1       Virat Kohli   34      80
2      Rohit Sharma   33      85
3      Suresh Raina   35      70
4    Jasprit Bumrah   32      80
5      Yuvraj Singh   40      65
6    Shikhar Dhawan   36      75
7   Ravindra Jadeja   33      75
8          KL Rahul   31      70
9     Hardik Pandya   32      80
10     Rishabh Pant   25      75
M.S. Dhoni

In [ ]:
value = df.iloc[2,3] # Index concepts in MYSQL -- Row and Column based indexing.
print("specific_selection values",value)

specific_selection values Mumbai Indians

In [112]:
data = df[df['Age'] > 30].iloc[:,:]

print("Filtered Data\n",data)

Filtered Data
             Player  Age  Rating                         Team
0       M.S. Dhoni   39      75          Chennai Super Kings
1      Virat Kohli   34      80  Royal Challengers Bangalore
2     Rohit Sharma   33      85               Mumbai Indians
3     Suresh Raina   35      70          Chennai Super Kings
4   Jasprit Bumrah   32      80               Mumbai Indians
5     Yuvraj Singh   40      65                 Punjab Kings
6   Shikhar Dhawan   36      75               Delhi Capitals
7  Ravindra Jadeja   33      75          Chennai Super Kings
8         KL Rahul   31      70                 Punjab Kings
9    Hardik Pandya   32      80               Mumbai Indians

In [113]:
df.set_index('Player', inplace=True)
print(df)

                 Age  Rating                         Team
Player
M.S. Dhoni        39      75          Chennai Super Kings
Virat Kohli       34      80  Royal Challengers Bangalore
Rohit Sharma      33      85               Mumbai Indians
Suresh Raina      35      70          Chennai Super Kings
Jasprit Bumrah    32      80               Mumbai Indians
Yuvraj Singh      40      65                 Punjab Kings
Shikhar Dhawan    36      75               Delhi Capitals
Ravindra Jadeja   33      75          Chennai Super Kings
KL Rahul          31      70                 Punjab Kings
Hardik Pandya     32      80               Mumbai Indians
Rishabh Pant      25      75               Delhi Capitals

In [114]:
# Select specified cell
value=df.loc['M.S. Dhoni','Age']
print(value)

39

In [115]:
# Select multiple cells
values=df.loc[['M.S. Dhoni','Virat Kohli'],['Age','Team']]
print(values)

             Age                         Team
Player
M.S. Dhoni    39          Chennai Super Kings
Virat Kohli   34  Royal Challengers Bangalore

In [120]:
# Select slicing
values=df.loc[:,'Age':'Team']
print(values)

values=df.loc[:,'Age']
print(values)

                 Age  Rating                         Team
Player
M.S. Dhoni        39      75          Chennai Super Kings
Virat Kohli       34      80  Royal Challengers Bangalore
Rohit Sharma      33      85               Mumbai Indians
Suresh Raina      35      70          Chennai Super Kings
Jasprit Bumrah    32      80               Mumbai Indians
Yuvraj Singh      40      65                 Punjab Kings
Shikhar Dhawan    36      75               Delhi Capitals
Ravindra Jadeja   33      75          Chennai Super Kings
KL Rahul          31      70                 Punjab Kings
Hardik Pandya     32      80               Mumbai Indians
Rishabh Pant      25      75               Delhi Capitals
Player
M.S. Dhoni         39
Virat Kohli        34
Rohit Sharma       33
Suresh Raina       35
Jasprit Bumrah     32
Yuvraj Singh       40
Shikhar Dhawan     36
Ravindra Jadeja    33
KL Rahul           31
Hardik Pandya      32
Rishabh Pant       25
Name: Age, dtype: int64

In [127]:
# Filter datafame using multiple conditions
import pandas as pd
df=pd.DataFrame({
    'Name':['Alice','Bob','Charlie','Justin'],
    'Age':[25,30,35,28],
    'City':['Newyork','Bangalore','Hyd','London'],
    'Salary':[50000,60000,70000,80000]
})

# Age > 30 and City = 'Hyd  --&& --and operator
print(df[(df["Age"]>30) & (df["City"] == "Hyd")])

print(df[(df["City"] == 'Bangalore') | (df["Salary"] > 60000)])  # OR operator

print(df[df['City'].isin(['Hyd','London'])])  # Using isin() method to filter data based on a list of values.   


print(df[(df["Age"] > 25) & (df["City"].isin(['Hyd','London'])) & (df['Salary'] > 60000)])  # Multiple conditions with isin() method

      Name  Age City  Salary
2  Charlie   35  Hyd   70000
      Name  Age       City  Salary
1      Bob   30  Bangalore   60000
2  Charlie   35        Hyd   70000
3   Justin   28     London   80000
      Name  Age    City  Salary
2  Charlie   35     Hyd   70000
3   Justin   28  London   80000
      Name  Age    City  Salary
2  Charlie   35     Hyd   70000
3   Justin   28  London   80000

In [128]:
# Range Filtering
df1=df[(df['Age'] >= 30) & (df['Age'] <= 35)]
print(df1)

      Name  Age       City  Salary
1      Bob   30  Bangalore   60000
2  Charlie   35        Hyd   70000

In [129]:
# Safest and cleanst way is use between() method for range filtering.
df2=df[df['Age'].between(30,35)]
print(df2)

      Name  Age       City  Salary
1      Bob   30  Bangalore   60000
2  Charlie   35        Hyd   70000

In [133]:
df2=df[df["Name"].str.contains('a',case=False)]  # Case insensetive search for string contains.
print(df2)

df2=df[df["Name"].str.startswith('A')]  # Case insensetive search for string starts with.
print(df2)

df2=df[df["Name"].str.endswith('a')]  # Case insensetive search for string ends with.
print(df2)

      Name  Age     City  Salary
0    Alice   25  Newyork   50000
2  Charlie   35      Hyd   70000
    Name  Age     City  Salary
0  Alice   25  Newyork   50000
Empty DataFrame
Columns: [Name, Age, City, Salary]
Index: []

In [134]:
df2=df.query('Age > 25 and City in ["Hyd","London"] and Salary > 60000')
print(df2)

      Name  Age    City  Salary
2  Charlie   35     Hyd   70000
3   Justin   28  London   80000

In [135]:
df3=df[df['Age'].apply(lambda x: x > 25)]
print(df3)

      Name  Age       City  Salary
1      Bob   30  Bangalore   60000
2  Charlie   35        Hyd   70000
3   Justin   28     London   80000

In [136]:
# Filter null values
df4=df[df['City'].isnull()]
print(df4)
df5=df[df['City'].notnull()]
print(df5)

Empty DataFrame
Columns: [Name, Age, City, Salary]
Index: []
      Name  Age       City  Salary
0    Alice   25    Newyork   50000
1      Bob   30  Bangalore   60000
2  Charlie   35        Hyd   70000
3   Justin   28     London   80000

In [137]:
# combine conditions
cond1=df['Age'] > 25
cond2=df['City'].isin(['Hyd','London'])
df3=df[cond1 & cond2]
print(df3)

      Name  Age    City  Salary
2  Charlie   35     Hyd   70000
3   Justin   28  London   80000

In [138]:
# Fliter and also select specific columns.
df4=df.loc[(df['Age'] > 25) & (df['City'].isin(['Hyd','London'])), ['Name','City']]
print(df4)

      Name    City
2  Charlie     Hyd
3   Justin  London

In [139]:
# Advanced Trick for chaining.

df5=df.loc[df['Age'] > 25].loc[df['City'].isin(['Hyd','London'])][['Name','City']]

print(df5)

      Name    City
2  Charlie     Hyd
3   Justin  London

AND          &
OR           |
NOT          `
Multiple values isin()
Range        between()
Query        df.query()

In [140]:
# ~ not 

df5=df.loc[~(df['Age'] > 25)]
print(df5)

    Name  Age     City  Salary
0  Alice   25  Newyork   50000

pandas.eval() evailates a string expession using pandas objects (DataFrame/Series)

pandas.eval(expr,inplace=False,**kwargs)


df.eval(expr,inplace=False)

In [144]:
import pandas as pd
df =pd.DataFrame({
    'A':[1,2,3],
    'B':[4,5,6],
})
#df.eval('A + B')
df.eval('C = A + B', inplace=True)
print(df)

df.eval('D = A * B', inplace=True)
print(df)

df.eval('E = (A+B) * 2', inplace=True)
print(df)

   A  B  C
0  1  4  5
1  2  5  7
2  3  6  9
   A  B  C   D
0  1  4  5   4
1  2  5  7  10
2  3  6  9  18
   A  B  C   D   E
0  1  4  5   4  10
1  2  5  7  10  14
2  3  6  9  18  18

eval()    vs  query()

Purpose   Compute Expressions       Filter rows.
Output    Series/DataFrames         Filtered DF.
Ex:       df.eval('C=A+B')          df.query('A>3')

In [ ]:
df.eval('total_marks=math+science+english', inplace=True)

df.eval('avg_marks=total_marks/3', inplace=True)

In [ ]:
df.eval('profit = revenue - cost', inplace=True)
df.eval('profit_margin = profit / revenue * 100', inplace=True)

df.eval('tax=profit * 0.3',inplace=True )

df.eval('final_price=price *(1 -discount)',inplace=True )


# SQl Like Expressions

df.eval('total= price * quantity', inplace=True)

eval() 

Large datasets --Performence .
Repetative convertions --transformations.
Dynamic fomula systems.
Clean ,redable pipelines for ML

In [146]:
data = {'Name':['Alice','Bob','Charlie'],
        'Age':[25,30,35],
        'Address':['Newyork','Bangalore','Hyd'],
        'Qualification':['Graduate','Postgraduate','PhD']}

data1={'Name':['David','Eve','Frank'],
        'Age':[28,32,40],
        'Address':['Chicago','Mumbai','Delhi'],
        'Qualification':['Graduate','Postgraduate','PhD']
}

df = pd.DataFrame(data,index=[0,1,2])

df1=pd.DataFrame(data1,index=[4,5,6])

print(df,"\n\n",df1)

      Name  Age    Address Qualification
0    Alice   25    Newyork      Graduate
1      Bob   30  Bangalore  Postgraduate
2  Charlie   35        Hyd           PhD

     Name  Age  Address Qualification
4  David   28  Chicago      Graduate
5    Eve   32   Mumbai  Postgraduate
6  Frank   40    Delhi           PhD

In [147]:
# Wanted to add / combine 2 datafames.

frames=[df,df1]
result=pd.concat(frames)
print(result)

      Name  Age    Address Qualification
0    Alice   25    Newyork      Graduate
1      Bob   30  Bangalore  Postgraduate
2  Charlie   35        Hyd           PhD
4    David   28    Chicago      Graduate
5      Eve   32     Mumbai  Postgraduate
6    Frank   40      Delhi           PhD

In [148]:
data = {'Name':['Alice','Bob','Charlie'],
        'Age':[25,30,35],
        'Address':['Newyork','Bangalore','Hyd'],
        'Qualification':['Graduate','Postgraduate','PhD']}

data1={'Name':['David','Eve','Frank'],
        'Age':[28,32,40],
        'Address':['Chicago','Mumbai','Delhi'],
        'Qualification':['Graduate','Postgraduate','PhD']
}

df = pd.DataFrame(data,index=[0,1,2])

df1=pd.DataFrame(data1,index=[2,3,5])

print(df,"\n\n",df1)

      Name  Age    Address Qualification
0    Alice   25    Newyork      Graduate
1      Bob   30  Bangalore  Postgraduate
2  Charlie   35        Hyd           PhD

     Name  Age  Address Qualification
2  David   28  Chicago      Graduate
3    Eve   32   Mumbai  Postgraduate
5  Frank   40    Delhi           PhD

In [149]:
result=pd.concat([df,df1],axis=1,join='inner')
print(result)

      Name  Age Address Qualification   Name  Age  Address Qualification
2  Charlie   35     Hyd           PhD  David   28  Chicago      Graduate

In [151]:
result=pd.concat([df,df1],axis=1,join='outer')
print(result)

      Name   Age    Address Qualification   Name   Age  Address Qualification
0    Alice  25.0    Newyork      Graduate    NaN   NaN      NaN           NaN
1      Bob  30.0  Bangalore  Postgraduate    NaN   NaN      NaN           NaN
2  Charlie  35.0        Hyd           PhD  David  28.0  Chicago      Graduate
3      NaN   NaN        NaN           NaN    Eve  32.0   Mumbai  Postgraduate
5      NaN   NaN        NaN           NaN  Frank  40.0    Delhi           PhD

In [152]:
result=pd.concat([df,df1],axis=1,sort=False)
print(result)

      Name   Age    Address Qualification   Name   Age  Address Qualification
0    Alice  25.0    Newyork      Graduate    NaN   NaN      NaN           NaN
1      Bob  30.0  Bangalore  Postgraduate    NaN   NaN      NaN           NaN
2  Charlie  35.0        Hyd           PhD  David  28.0  Chicago      Graduate
3      NaN   NaN        NaN           NaN    Eve  32.0   Mumbai  Postgraduate
5      NaN   NaN        NaN           NaN  Frank  40.0    Delhi           PhD

In [153]:
result=pd.concat([df,df1], ignore_index=True)
print(result)

      Name  Age    Address Qualification
0    Alice   25    Newyork      Graduate
1      Bob   30  Bangalore  Postgraduate
2  Charlie   35        Hyd           PhD
3    David   28    Chicago      Graduate
4      Eve   32     Mumbai  Postgraduate
5    Frank   40      Delhi           PhD

In [154]:
frames=[df,df1]
result=pd.concat(frames, keys=['x','y'])
print(result)

        Name  Age    Address Qualification
x 0    Alice   25    Newyork      Graduate
  1      Bob   30  Bangalore  Postgraduate
  2  Charlie   35        Hyd           PhD
y 2    David   28    Chicago      Graduate
  3      Eve   32     Mumbai  Postgraduate
  5    Frank   40      Delhi           PhD

In [156]:
import pandas as pd
data1 = {'Name':['Alice','Bob','Charlie'],
        'Age':[25,30,35],
        'Address':['Newyork','Bangalore','Hyd'],
        'Qualification':['Graduate','Postgraduate','PhD']}
df=pd.DataFrame(data1,index=[0,1,2])


s1=pd.Series([10000,20000,30000],name='Salary')


print(df,"\n\n",s1)

      Name  Age    Address Qualification
0    Alice   25    Newyork      Graduate
1      Bob   30  Bangalore  Postgraduate
2  Charlie   35        Hyd           PhD

 0    10000
1    20000
2    30000
Name: Salary, dtype: int64

In [157]:
res =pd.concat([df,s1],axis=1)
print(res)

      Name  Age    Address Qualification  Salary
0    Alice   25    Newyork      Graduate   10000
1      Bob   30  Bangalore  Postgraduate   20000
2  Charlie   35        Hyd           PhD   30000

In [160]:
import pandas as pd
data1 = {'Key1':['K0','K1','K2','K3'],
         'Name':['Alice','Bob','Charlie','David'],
         'Age':[25,30,35,40]}
data2={'Key1':['K0','K1','K2','K3'],
         'City':['Newyork','Bangalore','Hyd','London'],
         'Qualification':['Graduate','Postgraduate','PhD','Graduate']}

df=pd.DataFrame(data1)
df1=pd.DataFrame(data2)

print(df,"\n\n",df1)

  Key1     Name  Age
0   K0    Alice   25
1   K1      Bob   30
2   K2  Charlie   35
3   K3    David   40

   Key1       City Qualification
0   K0    Newyork      Graduate
1   K1  Bangalore  Postgraduate
2   K2        Hyd           PhD
3   K3     London      Graduate

In [161]:
# Merging of DF using a key.
result=pd.merge(df,df1,on='Key1')
print(result)

  Key1     Name  Age       City Qualification
0   K0    Alice   25    Newyork      Graduate
1   K1      Bob   30  Bangalore  Postgraduate
2   K2  Charlie   35        Hyd           PhD
3   K3    David   40     London      Graduate

In [162]:
import pandas as pd
data1={'Key':['K0','K1','K2','K3'],
       'Key1':['K0','K1','K0','K1'],
       'Name':['Alice','Bob','Charlie','David'],
       'Age':[25,30,35,40]}

data2={'Key':['K0','K1','K2','K3'],
       'Key1':['K0','K0','K0','K0'],
       'Address':['123 Main St','456 Oak Ave','789 Pine Rd','321 Elm Dr'],
       'Qualification':['Graduate','Postgraduate','PhD','Graduate']}

df=pd.DataFrame(data1)
df1=pd.DataFrame(data2)

print(df,"\n\n",df1)

  Key Key1     Name  Age
0  K0   K0    Alice   25
1  K1   K1      Bob   30
2  K2   K0  Charlie   35
3  K3   K1    David   40

   Key Key1      Address Qualification
0  K0   K0  123 Main St      Graduate
1  K1   K0  456 Oak Ave  Postgraduate
2  K2   K0  789 Pine Rd           PhD
3  K3   K0   321 Elm Dr      Graduate

In [165]:
res=pd.merge(df,df1,how='left',on=['Key','Key1'])
print(res)

  Key Key1     Name  Age      Address Qualification
0  K0   K0    Alice   25  123 Main St      Graduate
1  K1   K1      Bob   30          NaN           NaN
2  K2   K0  Charlie   35  789 Pine Rd           PhD
3  K3   K1    David   40          NaN           NaN

In [166]:
res=pd.merge(df,df1,how='right',on=['Key','Key1'])
print(res)

  Key Key1     Name   Age      Address Qualification
0  K0   K0    Alice  25.0  123 Main St      Graduate
1  K1   K0      NaN   NaN  456 Oak Ave  Postgraduate
2  K2   K0  Charlie  35.0  789 Pine Rd           PhD
3  K3   K0      NaN   NaN   321 Elm Dr      Graduate

In [167]:
res=pd.merge(df,df1,how='outer',on=['Key','Key1'])
print(res)

  Key Key1     Name   Age      Address Qualification
0  K0   K0    Alice  25.0  123 Main St      Graduate
1  K1   K0      NaN   NaN  456 Oak Ave  Postgraduate
2  K1   K1      Bob  30.0          NaN           NaN
3  K2   K0  Charlie  35.0  789 Pine Rd           PhD
4  K3   K0      NaN   NaN   321 Elm Dr      Graduate
5  K3   K1    David  40.0          NaN           NaN

In [168]:
res=pd.merge(df,df1,how='inner',on=['Key','Key1'])
print(res)

  Key Key1     Name  Age      Address Qualification
0  K0   K0    Alice   25  123 Main St      Graduate
1  K2   K0  Charlie   35  789 Pine Rd           PhD

In [169]:
data1={'Name':['Alice','Bob','Charlie','john'],
       'Age':[25,30,35,45]}

data2={'Address':['123 Main St','456 Oak Ave','789 Pine Rd','321 Elm Dr'],
       'Qualification':['Graduate','Postgraduate','PhD','Graduate']}

df1=pd.DataFrame(data1,index=['K0','K1','K2','K3'])

df2=pd.DataFrame(data2,index=['K0','K2','K3','K4'])

print(df1,"\n\n",df2)

       Name  Age
K0    Alice   25
K1      Bob   30
K2  Charlie   35
K3     john   45

         Address Qualification
K0  123 Main St      Graduate
K2  456 Oak Ave  Postgraduate
K3  789 Pine Rd           PhD
K4   321 Elm Dr      Graduate

In [171]:
res=df1.join(df2)
print(res)

       Name  Age      Address Qualification
K0    Alice   25  123 Main St      Graduate
K1      Bob   30          NaN           NaN
K2  Charlie   35  456 Oak Ave  Postgraduate
K3     john   45  789 Pine Rd           PhD

In [174]:
res=df1.join(df2,how='inner')
print(res)

       Name  Age      Address Qualification
K0    Alice   25  123 Main St      Graduate
K2  Charlie   35  456 Oak Ave  Postgraduate
K3     john   45  789 Pine Rd           PhD

In [175]:
res=df1.join(df2,how='outer')
print(res)

       Name   Age      Address Qualification
K0    Alice  25.0  123 Main St      Graduate
K1      Bob  30.0          NaN           NaN
K2  Charlie  35.0  456 Oak Ave  Postgraduate
K3     john  45.0  789 Pine Rd           PhD
K4      NaN   NaN   321 Elm Dr      Graduate

In [178]:
res=df1.join(df2,on='Name')
print(res)

       Name  Age Address Qualification
K0    Alice   25     NaN           NaN
K1      Bob   30     NaN           NaN
K2  Charlie   35     NaN           NaN
K3     john   45     NaN           NaN

sort_values()  ---makes us to easy to sort our df by a single column--sorts in ascending order --We can customize this to desc order.

In [180]:
data = {'Name':['Alice','Bob','Charlie','john'],
       'Age':[25,30,35,45],
       'Score':[85,90,95,80]}

df=pd.DataFrame(data)

sorted_df=df.sort_values(by='Age',ascending=False)
print(sorted_df)

      Name  Age  Score
3     john   45     80
2  Charlie   35     95
1      Bob   30     90
0    Alice   25     85

By ---column to use fo sorting.
ascending : boolean --True(default) asc and flase --desc.
inplace: If true the original  df is modified otherwise a new sorted df is returned.
na_poisition: Control where NAN values to be placed.
igonor_index: if True : resets the index after sorting